// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonNamestaja.Infrastructure.Data;

#nullable disable

namespace SalonNamestaja.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613202044_RemoveKupacProdavacAddApplicationUserId")]
    partial class RemoveKupacProdavacAddApplicationUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Boja", b =>
                {
                    b.Property<int>("BojaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BojaID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BojaID");

                    b.ToTable("Boje");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dimenzije", b =>
                {
                    b.Property<int>("DimenzijeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DimenzijeID"));

                    b.Property<double>("Dubina")
                        .HasColumnType("float");

                    b.Property<double>("Sirina")
                        .HasColumnType("float");

                    b.Property<double>("Visina")
                        .HasColumnType("float");

                    b.HasKey("DimenzijeID");

                    b.ToTable("Dimenzije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dostava", b =>
                {
                    b.Property<int>("DostavaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DostavaID"));

                    b.Property<double>("CenaDostave")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumDostave")
                        .HasColumnType("datetime2");

                    b.Property<int>("PorudzbinaID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DostavaID");

                    b.HasIndex("PorudzbinaID")
                        .IsUnique();

                    b.ToTable("Dostave");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Kategorija", b =>
                {
                    b.Property<int>("KategorijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorijaID");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Materijal", b =>
                {
                    b.Property<int>("MaterijalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterijalID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterijalID");

                    b.ToTable("Materijali");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.PodKategorija", b =>
                {
                    b.Property<int>("PodkategorijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PodkategorijaID"));

                    b.Property<int>("KategorijaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PodkategorijaID");

                    b.HasIndex("KategorijaID");

                    b.ToTable("PodKategorije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Porudzbina", b =>
                {
                    b.Property<int>("PorudzbinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PorudzbinaID"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatumVreme")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UkupanIznos")
                        .HasColumnType("float");

                    b.HasKey("PorudzbinaID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Porudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvod", b =>
                {
                    b.Property<int>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodID"));

                    b.Property<int>("BojaID")
                        .HasColumnType("int");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("DimenzijeID")
                        .HasColumnType("int");

                    b.Property<int>("MaterijalID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PodkategorijaID")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodjacID")
                        .HasColumnType("int");

                    b.Property<string>("SlikaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StanjeNaLageru")
                        .HasColumnType("int");

                    b.Property<string>("TipProizvoda")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ProizvodID");

                    b.HasIndex("BojaID");

                    b.HasIndex("DimenzijeID");

                    b.HasIndex("MaterijalID");

                    b.HasIndex("PodkategorijaID");

                    b.HasIndex("ProizvodjacID");

                    b.ToTable("Proizvodi");

                    b.HasDiscriminator<string>("TipProizvoda").HasValue("Proizvod");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvodjac", b =>
                {
                    b.Property<int>("ProizvodjacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodjacID"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodjacID");

                    b.ToTable("Proizvodjaci");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.StavkaPorudzbine", b =>
                {
                    b.Property<int>("StavkaPorudzbinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StavkaPorudzbinaID"));

                    b.Property<double>("CenaPoKomadu")
                        .HasColumnType("float");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("PorudzbinaID")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int");

                    b.Property<int>("Rb")
                        .HasColumnType("int");

                    b.HasKey("StavkaPorudzbinaID");

                    b.HasIndex("PorudzbinaID");

                    b.HasIndex("ProizvodID");

                    b.ToTable("StavkePorudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Garnitura", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<string>("Orijentacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Punjenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rasklopiva")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Garnitura");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Krevet", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<string>("DimenzijaDuseka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImaSanduk")
                        .HasColumnType("bit");

                    b.Property<string>("TipKreveta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Krevet");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Orman", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<int>("BrojVrata")
                        .HasColumnType("int");

                    b.Property<bool>("ImaOgledalo")
                        .HasColumnType("bit");

                    b.Property<string>("TipVrata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Orman");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Sto", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<string>("Oblik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rasklopiv")
                        .HasColumnType("bit");

                    b.ToTable("Proizvodi", t =>
                        {
                            t.Property("BrojMesta")
                                .HasColumnName("Sto_BrojMesta");
                        });

                    b.HasDiscriminator().HasValue("Sto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SalonNamestaja.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SalonNamestaja.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SalonNamestaja.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dostava", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Porudzbina", "Porudzbina")
                        .WithOne("Dostava")
                        .HasForeignKey("SalonNamestaja.Domain.Dostava", "PorudzbinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.PodKategorija", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Kategorija", "Kategorija")
                        .WithMany("Podkategorije")
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Porudzbina", b =>
                {
                    b.HasOne("SalonNamestaja.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvod", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Boja", "Boja")
                        .WithMany("Proizvodi")
                        .HasForeignKey("BojaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Dimenzije", "Dimenzije")
                        .WithMany("Proizvodi")
                        .HasForeignKey("DimenzijeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Materijal", "Materijal")
                        .WithMany("Proizvodi")
                        .HasForeignKey("MaterijalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.PodKategorija", "Podkategorija")
                        .WithMany("Proizvodi")
                        .HasForeignKey("PodkategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Proizvodjac", "Proizvodjac")
                        .WithMany("Proizvodi")
                        .HasForeignKey("ProizvodjacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boja");

                    b.Navigation("Dimenzije");

                    b.Navigation("Materijal");

                    b.Navigation("Podkategorija");

                    b.Navigation("Proizvodjac");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.StavkaPorudzbine", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Porudzbina", "Porudzbina")
                        .WithMany("StavkePorudzbine")
                        .HasForeignKey("PorudzbinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Proizvod", "Proizvod")
                        .WithMany("StavkePorudzbine")
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porudzbina");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Boja", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dimenzije", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Kategorija", b =>
                {
                    b.Navigation("Podkategorije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Materijal", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.PodKategorija", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Porudzbina", b =>
                {
                    b.Navigation("Dostava")
                        .IsRequired();

                    b.Navigation("StavkePorudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvod", b =>
                {
                    b.Navigation("StavkePorudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvodjac", b =>
                {
                    b.Navigation("Proizvodi");
                });
#pragma warning restore 612, 618
        }
    }
}
