// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonNamestajaAPI.Data;

#nullable disable

namespace SalonNamestajaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalonNamestaja.Domain.Boja", b =>
                {
                    b.Property<int>("BojaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BojaID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BojaID");

                    b.ToTable("Boje");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dimenzije", b =>
                {
                    b.Property<int>("DimenzijeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DimenzijeID"));

                    b.Property<double>("Dubina")
                        .HasColumnType("float");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int");

                    b.Property<double>("Sirina")
                        .HasColumnType("float");

                    b.Property<double>("Visina")
                        .HasColumnType("float");

                    b.HasKey("DimenzijeID");

                    b.HasIndex("ProizvodID")
                        .IsUnique();

                    b.ToTable("Dimenzije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dostava", b =>
                {
                    b.Property<int>("DostavaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DostavaID"));

                    b.Property<double>("CenaDostave")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumDostave")
                        .HasColumnType("datetime2");

                    b.Property<int>("PorudzbinaID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DostavaID");

                    b.HasIndex("PorudzbinaID")
                        .IsUnique();

                    b.ToTable("Dostave");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Kategorija", b =>
                {
                    b.Property<int>("KategorijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorijaID");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Kupac", b =>
                {
                    b.Property<int>("KupacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KupacID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PIB")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipKupca")
                        .HasColumnType("int");

                    b.HasKey("KupacID");

                    b.ToTable("Kupci");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Materijal", b =>
                {
                    b.Property<int>("MaterijalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterijalID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterijalID");

                    b.ToTable("Materijali");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.PodKategorija", b =>
                {
                    b.Property<int>("PodkategorijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PodkategorijaID"));

                    b.Property<int>("KategorijaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PodkategorijaID");

                    b.HasIndex("KategorijaID");

                    b.ToTable("PodKategorije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Porudzbina", b =>
                {
                    b.Property<int>("PorudzbinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PorudzbinaID"));

                    b.Property<DateTime>("DatumVreme")
                        .HasColumnType("datetime2");

                    b.Property<int>("KupacID")
                        .HasColumnType("int");

                    b.Property<int>("ProdavacID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UkupanIznos")
                        .HasColumnType("float");

                    b.HasKey("PorudzbinaID");

                    b.HasIndex("KupacID");

                    b.HasIndex("ProdavacID");

                    b.ToTable("Porudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Prodavac", b =>
                {
                    b.Property<int>("ProdavacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdavacID"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdavacID");

                    b.ToTable("Prodavci");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvod", b =>
                {
                    b.Property<int>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodID"));

                    b.Property<int>("BojaID")
                        .HasColumnType("int");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("DimenzijeID")
                        .HasColumnType("int");

                    b.Property<int>("MaterijalID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PodkategorijaID")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodjacID")
                        .HasColumnType("int");

                    b.Property<int>("StanjeNaLageru")
                        .HasColumnType("int");

                    b.Property<string>("TipProizvoda")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ProizvodID");

                    b.HasIndex("BojaID");

                    b.HasIndex("MaterijalID");

                    b.HasIndex("PodkategorijaID");

                    b.HasIndex("ProizvodjacID");

                    b.ToTable("Proizvodi");

                    b.HasDiscriminator<string>("TipProizvoda").HasValue("Proizvod");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvodjac", b =>
                {
                    b.Property<int>("ProizvodjacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodjacID"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodjacID");

                    b.ToTable("Proizvodjaci");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.StavkaPorudzbine", b =>
                {
                    b.Property<int>("StavkaPorudzbinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StavkaPorudzbinaID"));

                    b.Property<double>("CenaPoKomadu")
                        .HasColumnType("float");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("PorudzbinaID")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int");

                    b.Property<int>("Rb")
                        .HasColumnType("int");

                    b.HasKey("StavkaPorudzbinaID");

                    b.HasIndex("PorudzbinaID");

                    b.HasIndex("ProizvodID");

                    b.ToTable("StavkePorudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Garnitura", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<string>("Orijentacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Punjenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rasklopiva")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Garnitura");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Krevet", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<string>("DimenzijaDuseka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImaSanduk")
                        .HasColumnType("bit");

                    b.Property<string>("TipKreveta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Krevet");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Orman", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<int>("BrojVrata")
                        .HasColumnType("int");

                    b.Property<bool>("ImaOgledalo")
                        .HasColumnType("bit");

                    b.Property<string>("TipVrata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Orman");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Sto", b =>
                {
                    b.HasBaseType("SalonNamestaja.Domain.Proizvod");

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<string>("Oblik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rasklopiv")
                        .HasColumnType("bit");

                    b.ToTable("Proizvodi", t =>
                        {
                            t.Property("BrojMesta")
                                .HasColumnName("Sto_BrojMesta");
                        });

                    b.HasDiscriminator().HasValue("Sto");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dimenzije", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Proizvod", "Proizvod")
                        .WithOne("Dimenzije")
                        .HasForeignKey("SalonNamestaja.Domain.Dimenzije", "ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Dostava", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Porudzbina", "Porudzbina")
                        .WithOne("Dostava")
                        .HasForeignKey("SalonNamestaja.Domain.Dostava", "PorudzbinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.PodKategorija", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Kategorija", "Kategorija")
                        .WithMany("Podkategorije")
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Porudzbina", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Kupac", "Kupac")
                        .WithMany("Porudzbine")
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Prodavac", "Prodavac")
                        .WithMany("Porudzbine")
                        .HasForeignKey("ProdavacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kupac");

                    b.Navigation("Prodavac");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvod", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Boja", "Boja")
                        .WithMany("Proizvodi")
                        .HasForeignKey("BojaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Materijal", "Materijal")
                        .WithMany("Proizvodi")
                        .HasForeignKey("MaterijalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.PodKategorija", "Podkategorija")
                        .WithMany("Proizvodi")
                        .HasForeignKey("PodkategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Proizvodjac", "Proizvodjac")
                        .WithMany("Proizvodi")
                        .HasForeignKey("ProizvodjacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boja");

                    b.Navigation("Materijal");

                    b.Navigation("Podkategorija");

                    b.Navigation("Proizvodjac");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.StavkaPorudzbine", b =>
                {
                    b.HasOne("SalonNamestaja.Domain.Porudzbina", "Porudzbina")
                        .WithMany("StavkePorudzbine")
                        .HasForeignKey("PorudzbinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonNamestaja.Domain.Proizvod", "Proizvod")
                        .WithMany("StavkePorudzbine")
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porudzbina");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Boja", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Kategorija", b =>
                {
                    b.Navigation("Podkategorije");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Kupac", b =>
                {
                    b.Navigation("Porudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Materijal", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.PodKategorija", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Porudzbina", b =>
                {
                    b.Navigation("Dostava")
                        .IsRequired();

                    b.Navigation("StavkePorudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Prodavac", b =>
                {
                    b.Navigation("Porudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvod", b =>
                {
                    b.Navigation("Dimenzije")
                        .IsRequired();

                    b.Navigation("StavkePorudzbine");
                });

            modelBuilder.Entity("SalonNamestaja.Domain.Proizvodjac", b =>
                {
                    b.Navigation("Proizvodi");
                });
#pragma warning restore 612, 618
        }
    }
}
